platform :ios, '10.0'

target 'iOSClientApp' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for iOSClientApp
    pod 'FGRoute'
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'NSObject+Rx'
    pod 'RxBluetoothKit'
    pod 'SwiftyJSON'
    pod 'IQKeyboardManagerSwift'

end
